---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: weave-gitops-kind-kind
  url: ssh://git@github.com/luizbafilho/podinfo.git

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: wego-system
spec:
  chart:
    spec:
      chart: ./charts/podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo
  interval: 5m0s

