---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    weave-gitops.weave.works/app-identifier: wego-9c4f37ccbc3eba62923b255c22cd105d
  name: podinfo
  namespace: wego-system
spec:
  path: ./kustomize
  url: ssh://git@github.com/luizbafilho/podinfo.git
