---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    weave-gitops.weave.works/app-identifier: wego-ed3e1332b635f4aa9213c7e646cab3c9
  name: podinfo
  namespace: wego-system
spec:
  path: ./
  url: ssh://git@github.com/luizbafilho/podinfo.git
