---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    weave-gitops.weave.works/app-identifier: wego-0af49c2c73786c6f7eb8e83ddbf87710
  name: podinfo
  namespace: wego-system
spec:
  deployment_type: kustomize
  path: kustomize
  url: ssh://git@github.com/luizbafilho/podinfo.git
