---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: wego-system
  labels:
    weave-gitops.weave.works/app-identifier: wego-77f727f57c27130567f737afbfac5d00
spec:
  path: ./manifests
  url: ssh://git@github.com/luizbafilho/podinfo.git
